apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .settings.app.name }}"
  namespace: "{{ .settings.app.namespace }}"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "{{ .settings.app.name }}"
  template:
    metadata:
      labels:
        app: "{{ .settings.app.name }}"
    spec:
      containers:
      - name: app
        image: nginx:1.20
        env:
        - name: DATABASE_SECRET
          valueFrom:
            secretKeyRef:
              name: "{{ .ejson.metadata.name }}"
              key: database-secret
